---
language: node_js
node_js: 6

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

env:
  global:
  - JOBS=1

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1

install:
- travis_retry yarn install --pure-lockfile

before_script:
- greenkeeper-lockfile-update

script:
- yarn test

after_script:
- greenkeeper-lockfile-upload
- codeclimate-test-reporter < coverage/lcov.info

before_deploy:
  - ember build --prod

deploy:
  provider: firebase
  token:
    secure: ${FIREBASE_TOKEN}
  project: ${PROJECT_NAME}

cache:
  yarn: true
  directories:
  - node_modules
